var entrada = require("readline-sync")

// questao 3
// var num = parseFloat(entrada.question("Digite um numero"))
// var num2 = parseFloat(entrada.question("Digite outro numero"))
// var soma = (num+num2);
// console.log(`A soma desses numeros e de: ${soma}`)

// // questao 4

// var num = parseFloat(entrada.question("Digite um numero"))
// var num2 = parseFloat(entrada.question("Digite outro numero"))
// var num3 = parseFloat(entrada.question("Digite mais um numero"))
// var md = (num+num2+num3) /3;
// console.log(`A media desses numeros e de: ${md}`)

// questao 10






